---

- hosts: all
  become: yes
  gather_facts: yes

  tasks:
  - name: Copy systemd descriptor
    copy:
      src: src/main/systemd/spring-petclinic.service
      dest: /etc/systemd/system/spring-petclinic.service
    notify:
    - reload systemd

  - name: Copy spring-petclinic
    copy:
      src: target/spring-petclinic.jar
      dest: /opt/spring-petclinic.jar
      owner: deploy
      mode: u+rwx
    notify:
    - restart service

  - name: Enable service
    service:
      name: spring-petclinic
      enabled: yes

  handlers:
  - name: reload systemd
    systemd:
      name: spring-petclinic
      daemon_reload: yes
  
  - name: restart service
    service: 
      name: spring-petclinic
      state: restarted

